function [I_Q,data] = modulation(bit_num,r)

% ******************************Fill data set *******************************************************

    data_1_bin = randi([0 1],bit_num*r,1);                      
    if (r==1)
        data_bin =data_1_bin;
    elseif (r==2)
        data_bin =reshape(data_1_bin,[2,length(data_1_bin)/2]);
    elseif (r==4)
        data_bin =reshape(data_1_bin,[4,length(data_1_bin)/4]);
    elseif (r==6)
        data_bin =reshape(data_1_bin,[6,length(data_1_bin)/6]);
    elseif (r==8)
        data_bin =reshape(data_1_bin,[8,length(data_1_bin)/8]);
    else
        disp(" None. \n")
        data = [];
    end
    [data_row,data_col] = size(data_bin);
% ******************************Binary to gray *******************************************************
    for (j = 1:1:data_col)
        for (i = 1:1:data_row)
            if (i==1)
                data(i,j) = data_bin(i,j);
            else
                data(i,j) = xor(data_bin(i-1,j),data_bin(i,j));
            end
        end
    end

   %****************************BPSK constellation mapping************************************************************************
    if (r==1)
        for (i= 1:1:data_col)
            if(data(:,i)==[0])
                I(i)= -1; Q(i) = 0;
            else
                I(i)=  1; Q(i) = 0;
            end
        end
        %****************************QPSK constellation mapping************************************************************************
    elseif (r==2)
       for (i = 1:1:data_col)
            if ((data(1,i)==0) && (data(2,i)==0))
                I(i) = -1;
                Q(i) = -1;
            elseif ((data(1,i)==0) && (data(2,i)==1))
                I(i) = -1;
                Q(i) = +1;
            elseif ((data(1,i)==1) && (data(2,i)==0))
                I(i) = +1;
                Q(i) = -1;
            else
                I(i) = +1;
                Q(i) = +1;
            end
        end
        %****************************16-QAM constellation mapping**********************************************************************
    elseif (r==4)
        for (i = 1:1:data_col)
            if (data(1,i)==0 && data(2,i)==0)
                I(i) = -3;
            elseif (data(1,i)==0 && data(2,i)==1)
                I(i) = -1;
            elseif (data(1,i)==1 && data(2,i)==1)
                I(i) =  1;
            else
                I(i) =  3;
            end
        end
        for (i = 1:1:data_col)
            if (data(3,i)==1 && data(4,i)==0)
                Q(i) = -3;
            elseif (data(3,i)==1 && data(4,i)==1)
                Q(i) = -1;
            elseif (data(3,i)==0 && data(4,i)==1)
                Q(i) =  1;
            else
                Q(i) =  3;
            end
        end
        %****************************64-QAM constellation mapping**********************************************************************
    elseif (r==6)
        for (i = 1:1:data_col)
            if((data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==0) || ...
                    data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1)
                I(i) = -7;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1))
                I(i) = -5;
            elseif ((data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1))
                I(i) = -3;
            elseif ((data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1))
                I(i) = -1;
            elseif ((data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1))
                I(i) = +1;
            elseif ((data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1))
                I(i) = +3;
            elseif ((data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1))
                I(i) = +5;
            else
                I(i) = +7;
            end
        end
        for (i = 1:1:data_col)
            if((data(1,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0))
                Q(i) = -7;
            elseif ((data(1,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1) || ...
                    (data(1,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1))
                Q(i) = -5;
            elseif ((data(1,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1) || ...
                    (data(1,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1))
                Q(i) = -3;
            elseif ((data(1,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                Q(i) = -1;
            elseif ((data(1,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                Q(i) = +1;
            elseif ((data(1,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1) || ...
                    (data(1,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1))
                Q(i) = +3;
            elseif ((data(1,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1) || ...
                    (data(1,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1))
                Q(i) = +5;
            else
                Q(i) = +7;
            end
        end
            %****************************256-QAM constellation mapping*********************************************************************
    else %(r=8)********************************************************************************************************************
        for (i = 1:1:data_col)
            if ((data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                I(i) = -15;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = -13;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = -11;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0)  || ...
                    (data(1,i)==0 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1))
                I(i) = -9;
            elseif ((data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                I(i) = -7;
            elseif ((data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = -5;
            elseif ((data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = -3;
            elseif ((data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==0 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                I(i) = -1;
            elseif ((data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                I(i) = +1;
            elseif ((data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = +3;
            elseif ((data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = +5;
            elseif ((data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                I(i) = +7;
            elseif ((data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==0 && data(5,i)==1 && data(6,i)==0))
                I(i) = +9;
            elseif ((data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==1 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = +11;
            elseif((data(1,i)==1 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==0) || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==0 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(3,i)==0 && data(4,i)==1 && data(5,i)==1 && data(6,i)==0))
                I(i) = +13;
            else
                I(i) = +15;
            end
        end
        for (i = 1:1:data_col)
            if ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==0))
                Q(i) = -15;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1))
                Q(i) = -13;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1))
                Q(i) = -11;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0))
                Q(i) = -9;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0))
                Q(i) = -7;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1))
                Q(i) = -5;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1))
                Q(i) = -3;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==0 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0))
                Q(i) = -1;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==0))
                Q(i) = +1;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==0 && data(8,i)==1))
                Q(i) = +3;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==1))
                Q(i) = +5;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==1 && data(7,i)==1 && data(8,i)==0))
                Q(i) = +7;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==0))
                Q(i) = +9;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==0 && data(7,i)==1 && data(8,i)==1))
                Q(i) = +11;
            elseif ((data(1,i)==0 && data(2,i)==0 && data(5,i)==1 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1) || ...
                    (data(1,i)==0 && data(2,i)==1 && data(5,i)==1 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==1 && data(5,i)==1 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1)  || ...
                    (data(1,i)==1 && data(2,i)==0 && data(5,i)==1 && data(6,i)==0 && data(7,i)==0 && data(8,i)==1))
                Q(i) = +13;
            else
                Q(i) = +15;
            end
        end
    end



    %****************************I-Q normalization***************************************************************

    if (r==1)                %***************at BPSK*************************************************************
        factor = 1;
    elseif (r==2)            %***************at QPSK*************************************************************
        factor = 1/sqrt(2);
    elseif (r==4)            %***************at 16-QAM***********************************************************
        factor = 1/sqrt(10);
    elseif (r==6)            %***************at 64-QAM***********************************************************
        factor = 1/sqrt(4);
    elseif (r==8)            %***************at 256-QAM**********************************************************
        factor = 1/sqrt(170);
    else
        factor = 1;
    end

    for (i = 1:1:length(I))
        I_nor(i) = factor * I(i);
        Q_nor(i) = factor * Q(i);
    end


    %****************************I-Q mapping********************************************************************
    for (i = 1:1:length(I))
        I_Q(i) = complex(I_nor(i),Q_nor(i));
    end
end
